### ISSUE TITLE
pika version

### ISSUE THREAD

**Issue by KYSXD** [tracsa/cacahuate#111]
Running the daemon using `pika>=0.13` (i.e. `1.X`) results in:

```
[INFO] Declared queue cacahuate_process - cacahuate.loop:26                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/.../.local/share/virtualenvs/foo-DlrTvbfF/bin/cacahuated", line 10, in <module>                                                                                                       
    sys.exit(main())                                                                                                                                                                                               
  File "/home/.../.local/share/virtualenvs/foo-DlrTvbfF/lib/python3.6/site-packages/cacahuate/main.py", line 52, in main                                                                            
    loop.start()                                                                                                                                                                                                   
  File "/home/.../.local/share/virtualenvs/foo-DlrTvbfF/lib/python3.6/site-packages/cacahuate/loop.py", line 32, in start
    no_ack=self.config['RABBIT_NO_ACK'],
TypeError: basic_consume() got multiple values for argument 'queue'

```

**Comment by categulario** [comment]
se soluciona en #117
